name: PR Auto Documentation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for accurate diff

      # 2. Get PR diff
      - name: Get PR Diff
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }}...HEAD > pr_diff.txt

      # 3. Install Python (for OpenAI call)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 4. Install dependencies
      - name: Install deps
        run: pip install openai requests

      # 5. Run doc generation script
      - name: Generate Docs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: python .github/workflows/generate_docs.py
